### ISSUE TITLE
fixtures not loading

### ISSUE THREAD

**Issue by kapitanluffy** [hash-bang/Node-Mongoose-Scenario#1]
Fixtures does not work when I enable some fields.

Here it is when I disable a certain field (e.g. fullname)
![screenshot_39](https://cloud.githubusercontent.com/assets/485799/9311056/70368566-4546-11e5-9220-956bc6847d75.png)

Here it is when I enable it. It does not finish loading and does not throw any errors
![screenshot_40](https://cloud.githubusercontent.com/assets/485799/9311055/70326bc0-4546-11e5-9427-860f7148c12a.png)

Sometimes it happens with the password field or the location field.

**Comment by kapitanluffy** [comment]
The problem was next() was not called in one of the model's pre save hook. While debugging, I also noticed that the error is not properly thrown. I was made aware by the errors when I logged it in the console.

**Comment by hash-bang** [comment]
Ha ha. Great you managed to track it down.
